name: Generate Snake
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: dev-alt
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_dark_out_path: dist/github-contribution-grid-snake-dark.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      - name: List dist directory
        run: ls -la dist || echo "dist directory does not exist"
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
