name: Generate Snake

on:
  schedule:
    - cron: '0 */12 * * *'  # runs every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: dev-alt  # replace with your username
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_dark_out_path: dist/github-contribution-grid-snake-dark.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
